# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_book_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_review',
            name='rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='5', max_length=1),
        ),
    ]
