# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20160826_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
