# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 05:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20160917_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_review',
            name='for_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_review', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='for_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
